const data = {
  products: [
    {
      id: 1,
      title: "Red Bandana",
      description: "Red bandana with prints",
      price: 25,
      image: "/a-bandana1.jpg",
    },
    {
      id: 2,
      title: "Pink Bandana",
      description: "Pink bandana with mermaid print",
      price: 25,
      image: "/a-bandana2.jpg",
    },
    {
      id: 3,
      title: "Red Bow",
      description: "Classic red bow",
      price: 25,
      image: "/a-bow.jpg",
    },
    {
      id: 4,
      title: "Blue Plaid Cap",
      description: "Blue plaid cap",
      price: 25,
      image: "/a-cap.jpg",
    },
    {
      id: 5,
      title: "Cozy beanie",
      description: "Cozy beanie for the winter blues",
      price: 35,
      image: "/a-hat.jpg",
    },
    {
      id: 6,
      title: "Silver Paw Jacket",
      description: "Silver parka to keep the pooch warm in style",
      price: 75,
      image: "/a-jacket.jpg",
    },
    {
      id: 6,
      title: "Silver Parka",
      description: "Silver shiny jacket to keep the pooch warm in style",
      price: 75,
      image: "/a-jacket.jpg",
    },
    {
      id: 7,
      title: "Red Sweatshirt",
      description: "Red knitted sweatshirt with cuffed sleeves",
      price: 35,
      image: "/a-sweater.jpg",
    },
    {
      id: 8,
      title: "Striped Tie",
      description: "Silky red and navy striped necktie",
      price: 35,
      image: "/a-tie.jpg",
    },
    {
      id: 9,
      title: "Sunday Head Scarf",
      description: "Blue head scarf",
      price: 35,
      image: "/a-wrap.jpg",
    },
  ],
};
