export const data = {
  products: [
    {
      id: 1,
      name: "Red Bandana",
      description: "Red bandana with prints",
      price: 25,
      image: "/a-bandana1.jpg",
    },
    {
      id: 2,
      name: "Pink Bandana",
      description: "Pink bandana with mermaid print",
      price: 25,
      image: "/a-bandana2.jpg",
    },
    {
      id: 3,
      name: "Red Bow",
      description: "Classic red bow",
      price: 25,
      image: "/a-bow.jpg",
    },
    {
      id: 4,
      name: "Blue Plaid Cap",
      description: "Blue plaid cap",
      price: 25,
      image: "/a-cap.jpg",
    },
    {
      id: 5,
      name: "Cozy Beanie",
      description: "Cozy beanie for the winter blues",
      price: 35,
      image: "/a-hat.jpg",
    },
    {
      id: 6,
      name: "Silver Paw Jacket",
      description: "Silver parka to keep the pooch warm in style",
      price: 75,
      image: "/a-jacket.jpg",
    },
    {
      id: 7,
      name: "Blue Plaid Paw Jacket",
      description: "Blue plaid to keep the pooch warm in style",
      price: 75,
      image: "/a-jacket2.jpg",
    },
    {
      id: 8,
      name: "Striped Navy Sweater",
      description: "Striped navy sweater",
      price: 35,
      image: "/a-sweater3.jpg",
    },
    {
      id: 9,
      name: "Red Knitted Sweater",
      description: "Red knitted sweater",
      price: 35,
      image: "/a-sweater2.jpg",
    },

    {
      id: 10,
      name: "Red Sweatshirt",
      description: "Red knitted sweatshirt with cuffed sleeves",
      price: 35,
      image: "/a-sweater.jpg",
    },
    {
      id: 11,
      name: "Striped Tie",
      description: "Silky red and navy striped necktie",
      price: 35,
      image: "/a-tie.jpg",
    },
    {
      id: 12,
      name: "Sunday Head Scarf",
      description: "Blue head scarf",
      price: 35,
      image: "/a-wrap.jpg",
    },
    {
      id: 13,
      name: "Dog Bed",
      description: "Navy dog bed",
      price: 65,
      image: "/a-bed.jpg",
    },
    {
      id: 14,
      name: "Treats",
      description: "Chicken and salmon treats",
      price: 15,
      image: "/kibble.jpg",
    },
    {
      id: 15,
      name: "Pup Food Bowl Station",
      description:
        "Dishwasher safe food bowl to feed your pooch their daily meals with slip resistant mat",
      price: 35,
      image: "/foodbowl.jpg",
    },
  ],
};
